esphome:
  name: m16v2

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ../components/

# Enable logging
logger:

sensor:
  # Define ADC sensors first (set update_interval to never, as they will be sampled by ZMPT101B sensors)
  - platform: adc
    pin: 34
    id: adc34
    update_interval: never
    attenuation: 11db

  - platform: adc
    pin: 36
    id: adc36
    update_interval: never
    attenuation: 11db

  - platform: adc
    pin: 39
    id: adc39
    update_interval: never
    attenuation: 11db

  # ZMPT101B sensors reference the ADC sensors
  - platform: zmpt101b
    name: "m16--AI zmpt 34"
    sensor: adc34
    sensitivity: 500.0
    frequency: 50
    update_interval: 60s
    id: voltage_1

  - platform: zmpt101b
    name: "m16--AI zmpt 36"
    sensor: adc36
    sensitivity: 500.0
    frequency: 50
    update_interval: 60s
    id: voltage_2

  - platform: zmpt101b
    name: "m16--AI zmpt 39"
    sensor: adc39
    sensitivity: 500.0
    frequency: 50
    update_interval: 60s
    id: voltage_3
